# Generated by Django 5.2.14 on 2026-05-30 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProject',
            fields=[
                ('mp_id', models.AutoField(primary_key=True, serialize=False)),
                ('mp_name', models.TextField(verbose_name='Название КИПА')),
                ('allowed_Users', models.ManyToManyField(blank=True, related_name='allowed_main_projects', to=settings.AUTH_USER_MODEL, verbose_name='Доступ сотрудников')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_number', models.TextField(verbose_name='Номер проекта')),
                ('pr_name', models.TextField(blank=True, null=True, verbose_name='Название проекта')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Обьём')),
                ('status', models.TextField(blank=True, null=True, verbose_name='Статус')),
                ('main_project', models.ForeignKey(db_column='main_project_id', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.mainproject')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('workload', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Трудоёмкость')),
                ('task_name', models.TextField(verbose_name='Название задачи')),
                ('task_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('holder', models.ForeignKey(blank=True, db_column='holder_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project')),
            ],
        ),
    ]
