# Generated by Django 5.2.14 on 2026-06-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mainproject_gip'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Выдано', 'Выдано'), ('В работе', 'В работе'), ('Выполнено', 'Выполнено')], default='Выдано', max_length=20, verbose_name='Статус задачи'),
        ),
    ]
